env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"
install: |
   mvn -v
deploy:
  script: |
    mvn -v
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "release ${tag}"

