env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"
deploy:
  script:
    - mvn -v
release:
  script:
    - git checkout develop
    - mvn versions:set "-DnewVersion=${tag}"
    - git commit -am "release ${tag}"

