/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package monad.jni;

public final class BinlogType {
    public final static BinlogType LOG_BIN = new BinlogType("LOG_BIN", CMonadJNI.LOG_BIN_get());
    public final static BinlogType LOG_NONE = new BinlogType("LOG_NONE", CMonadJNI.LOG_NONE_get());
    private static BinlogType[] swigValues = {LOG_BIN, LOG_NONE};
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;

    private BinlogType(String swigName) {
        this.swigName = swigName;
        this.swigValue = swigNext++;
    }

    private BinlogType(String swigName, int swigValue) {
        this.swigName = swigName;
        this.swigValue = swigValue;
        swigNext = swigValue + 1;
    }

    private BinlogType(String swigName, BinlogType swigEnum) {
        this.swigName = swigName;
        this.swigValue = swigEnum.swigValue;
        swigNext = this.swigValue + 1;
    }

    public static BinlogType swigToEnum(int swigValue) {
        if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
            return swigValues[swigValue];
        for (int i = 0; i < swigValues.length; i++)
            if (swigValues[i].swigValue == swigValue)
                return swigValues[i];
        throw new IllegalArgumentException("No enum " + BinlogType.class + " with value " + swigValue);
    }

    public final int swigValue() {
        return swigValue;
    }

    public String toString() {
        return swigName;
    }
}

