/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package monad.jni;

public class CMonad implements CMonadConstants {
    public static int getMONAD_NATIVE_VERSION() {
        return CMonadJNI.MONAD_NATIVE_VERSION_get();
    }

    public static int LogOpen(String filename, int level, boolean is_threadsafe, long rotate_size) {
        return CMonadJNI.LogOpen__SWIG_0(filename, level, is_threadsafe, rotate_size);
    }

    public static int LogOpen(String filename, int level, boolean is_threadsafe) {
        return CMonadJNI.LogOpen__SWIG_1(filename, level, is_threadsafe);
    }

    public static int LogOpen(String filename, int level) {
        return CMonadJNI.LogOpen__SWIG_2(filename, level);
    }

    public static int LogOpen(String filename) {
        return CMonadJNI.LogOpen__SWIG_3(filename);
    }

    public static void SetLogLevel(int level) {
        CMonadJNI.SetLogLevel(level);
    }

    public static long HashString(String str) {
        return CMonadJNI.HashString(str);
    }

}
