/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package monad.jni;

public interface CMonadConstants {
    public final static String SYNC_WORKERS_ENDPOINT = CMonadJNI.SYNC_WORKERS_ENDPOINT_get();
    public final static String DATA_STAT_COUNT = CMonadJNI.DATA_STAT_COUNT_get();
    public final static String DATA_MAX_TIMESTAMP = CMonadJNI.DATA_MAX_TIMESTAMP_get();
}
