/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package monad.jni;

public class CMonadJNI {
    public final static native int SyncNoSQLManager_AddInstance(long jarg1, SyncNoSQLManager jarg1_, String jarg2, long jarg3, SyncNoSQL jarg3_);

    public final static native int SyncNoSQLManager_RemoveInstance(long jarg1, SyncNoSQLManager jarg1_, String jarg2);

    public final static native long SyncNoSQLManager_FindInstanceByHash(long jarg1, SyncNoSQLManager jarg1_, long jarg2);

    public final static native long SyncNoSQLManager_FindInstanceByName(long jarg1, SyncNoSQLManager jarg1_, String jarg2);

    public final static native long new_SyncNoSQLManager();

    public final static native void delete_SyncNoSQLManager(long jarg1);

    public final static native String SYNC_WORKERS_ENDPOINT_get();

    public final static native String DATA_STAT_COUNT_get();

    public final static native String DATA_MAX_TIMESTAMP_get();

    public final static native int MONAD_NATIVE_VERSION_get();

    public final static native int BINLOG_get();

    public final static native int KV_get();

    public final static native int REGION_INFO_get();

    public final static native int REGION_SEQ_get();

    public final static native int REGION_ID_INFO_get();

    public final static native int REGION_ID_SEQ_get();

    public final static native int ID_SEQ_get();

    public final static native int ID_STRING_get();

    public final static native int LOG_BIN_get();

    public final static native int LOG_NONE_get();

    public final static native int PUT_get();

    public final static native int DEL_get();

    public final static native int UPDATE_get();

    public final static native int COMMAND_UNKNOWN_get();

    public final static native int S_OK_get();

    public final static native int E_DATA_SAVE_get();

    public final static native int E_GET_get();

    public final static native int E_DATA_DELETE_get();

    public final static native int E_ELEMENT_NOT_FOUND_get();

    public final static native int E_NO_NODE_SERVER_get();

    public final static native int E_DATA_NOT_FOUND_get();

    public final static native int E_FAIL_TO_COMMIT_get();

    public final static native int E_INSTANCE_IS_NULL_get();

    public final static native int E_ID_SERVER_NOT_SET_get();

    public final static native void NoSQLOptions_cache_size_mb_set(long jarg1, NoSQLOptions jarg1_, long jarg2);

    public final static native long NoSQLOptions_cache_size_mb_get(long jarg1, NoSQLOptions jarg1_);

    public final static native void NoSQLOptions_write_buffer_mb_set(long jarg1, NoSQLOptions jarg1_, long jarg2);

    public final static native long NoSQLOptions_write_buffer_mb_get(long jarg1, NoSQLOptions jarg1_);

    public final static native void NoSQLOptions_max_open_files_set(long jarg1, NoSQLOptions jarg1_, long jarg2);

    public final static native long NoSQLOptions_max_open_files_get(long jarg1, NoSQLOptions jarg1_);

    public final static native void NoSQLOptions_log_keeped_num_set(long jarg1, NoSQLOptions jarg1_, long jarg2);

    public final static native long NoSQLOptions_log_keeped_num_get(long jarg1, NoSQLOptions jarg1_);

    public final static native long new_NoSQLOptions();

    public final static native void delete_NoSQLOptions(long jarg1);

    public final static native long new_NoSQLSupport(String jarg1, long jarg2, NoSQLOptions jarg2_);

    public final static native void delete_NoSQLSupport(long jarg1);

    public final static native byte[] NoSQLSupport_RawGet(long jarg1, NoSQLSupport jarg1_, byte[] jarg2);

    public final static native int NoSQLSupport_RawPut(long jarg1, NoSQLSupport jarg1_, byte[] jarg2, byte[] jarg3);

    public final static native int NoSQLSupport_GetDataStatCount(long jarg1, NoSQLSupport jarg1_);

    public final static native long new_NodeIdNoSQL(String jarg1, long jarg2, NoSQLOptions jarg2_);

    public final static native byte[] NodeIdNoSQL_GetId(long jarg1, NodeIdNoSQL jarg1_, int jarg2);

    public final static native int NodeIdNoSQL_GetIdSeq(long jarg1, NodeIdNoSQL jarg1_, byte[] jarg2);

    public final static native void delete_NodeIdNoSQL(long jarg1);

    public final static native long new_NodeNoSQL(String jarg1, long jarg2, NoSQLOptions jarg2_);

    public final static native void delete_NodeNoSQL(long jarg1);

    public final static native void NodeNoSQL_SetIdNoSQL(long jarg1, NodeNoSQL jarg1_, long jarg2, NodeIdNoSQL jarg2_);

    public final static native byte[] NodeNoSQL_Get(long jarg1, NodeNoSQL jarg1_, byte[] jarg2);

    public final static native byte[] NodeNoSQL_FindNextBinlog(long jarg1, NodeNoSQL jarg1_, long jarg2);

    public final static native byte[] NodeNoSQL_GetId(long jarg1, NodeNoSQL jarg1_, long jarg2);

    public final static native int NodeNoSQL_Del(long jarg1, NodeNoSQL jarg1_, byte[] jarg2);

    public final static native long NodeNoSQL_GetLastLogSeq(long jarg1, NodeNoSQL jarg1_);

    public final static native void NodeNoSQL_DeleteBinlog(long jarg1, NodeNoSQL jarg1_, long jarg2);

    public final static native int NodeNoSQL_StartSyncData(long jarg1, NodeNoSQL jarg1_, String jarg2, String jarg3, short jarg4);

    public final static native void NodeNoSQL_SyncDataWorker(long jarg1, NodeNoSQL jarg1_, String jarg2, String jarg3, short jarg4);

    public final static native long NodeNoSQL_DoSyncData(long jarg1, NodeNoSQL jarg1_, String jarg2, String jarg3, short jarg4);

    public final static native void NodeNoSQL_StopNoSQL(long jarg1, NodeNoSQL jarg1_);

    public final static native long new_SyncIdNoSQL(String jarg1, long jarg2, NoSQLOptions jarg2_);

    public final static native int SyncIdNoSQL_FindRegionMaxIdSeq(long jarg1, SyncIdNoSQL jarg1_, short jarg2);

    public final static native void SyncIdNoSQL_AddRegion(long jarg1, SyncIdNoSQL jarg1_, short jarg2);

    public final static native void SyncIdNoSQL_RemoveRegion(long jarg1, SyncIdNoSQL jarg1_, short jarg2);

    public final static native void delete_SyncIdNoSQL(long jarg1);

    public final static native long new_SyncNoSQL(String jarg1, long jarg2, NoSQLOptions jarg2_);

    public final static native void SyncNoSQL_SetSyncIdNoSQL(long jarg1, SyncNoSQL jarg1_, long jarg2, SyncIdNoSQL jarg2_);

    public final static native int SyncNoSQL_FindRegionMaxDataSeq(long jarg1, SyncNoSQL jarg1_, short jarg2);

    public final static native int SyncNoSQL_FindRegionMaxIdSeq(long jarg1, SyncNoSQL jarg1_, short jarg2);

    public final static native long SyncNoSQL_FindRegionMaxTransSeq(long jarg1, SyncNoSQL jarg1_, short jarg2);

    public final static native byte[] SyncNoSQL_GetRegionDataInfo(long jarg1, SyncNoSQL jarg1_);

    public final static native int SyncNoSQL_Del(long jarg1, SyncNoSQL jarg1_, byte[] jarg2);

    public final static native int SyncNoSQL_UpdateDataTimestamp(long jarg1, SyncNoSQL jarg1_, long jarg2);

    public final static native void SyncNoSQL_AddRegion(long jarg1, SyncNoSQL jarg1_, short jarg2, long jarg3);

    public final static native void SyncNoSQL_RemoveRegion(long jarg1, SyncNoSQL jarg1_, short jarg2);

    public final static native byte[] SyncNoSQL_FindNextBinlog(long jarg1, SyncNoSQL jarg1_, short jarg2, long jarg3);

    public final static native void SyncNoSQL_DeleteRegionBinlog(long jarg1, SyncNoSQL jarg1_, short jarg2, long jarg3);

    public final static native int SyncNoSQL_Put2(long jarg1, SyncNoSQL jarg1_, byte[] jarg2, byte[] jarg3, long jarg4, byte[] jarg5);

    public final static native void delete_SyncNoSQL(long jarg1);

    public final static native long new_SyncServer();

    public final static native int SyncServer_Start(long jarg1, SyncServer jarg1_, String jarg2);

    public final static native int SyncServer_StartWorkers(long jarg1, SyncServer jarg1_, int jarg2);

    public final static native void SyncServer_StopServer(long jarg1, SyncServer jarg1_);

    public final static native void delete_SyncServer(long jarg1);

    public final static native int LogOpen__SWIG_0(String jarg1, int jarg2, boolean jarg3, long jarg4);

    public final static native int LogOpen__SWIG_1(String jarg1, int jarg2, boolean jarg3);

    public final static native int LogOpen__SWIG_2(String jarg1, int jarg2);

    public final static native int LogOpen__SWIG_3(String jarg1);

    public final static native void SetLogLevel(int jarg1);

    public final static native long HashString(String jarg1);

    public final static native long NodeIdNoSQL_SWIGUpcast(long jarg1);

    public final static native long NodeNoSQL_SWIGUpcast(long jarg1);

    public final static native long SyncIdNoSQL_SWIGUpcast(long jarg1);

    public final static native long SyncNoSQL_SWIGUpcast(long jarg1);

    public final static native long SyncServer_SWIGUpcast(long jarg1);
}
