/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package monad.jni;

public final class DataType {
    public final static DataType BINLOG = new DataType("BINLOG", CMonadJNI.BINLOG_get());
    public final static DataType KV = new DataType("KV", CMonadJNI.KV_get());
    public final static DataType REGION_INFO = new DataType("REGION_INFO", CMonadJNI.REGION_INFO_get());
    public final static DataType REGION_SEQ = new DataType("REGION_SEQ", CMonadJNI.REGION_SEQ_get());
    public final static DataType REGION_ID_INFO = new DataType("REGION_ID_INFO", CMonadJNI.REGION_ID_INFO_get());
    public final static DataType REGION_ID_SEQ = new DataType("REGION_ID_SEQ", CMonadJNI.REGION_ID_SEQ_get());
    public final static DataType ID_SEQ = new DataType("ID_SEQ", CMonadJNI.ID_SEQ_get());
    public final static DataType ID_STRING = new DataType("ID_STRING", CMonadJNI.ID_STRING_get());
    private static DataType[] swigValues = {BINLOG, KV, REGION_INFO, REGION_SEQ, REGION_ID_INFO, REGION_ID_SEQ, ID_SEQ, ID_STRING};
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;

    private DataType(String swigName) {
        this.swigName = swigName;
        this.swigValue = swigNext++;
    }

    private DataType(String swigName, int swigValue) {
        this.swigName = swigName;
        this.swigValue = swigValue;
        swigNext = swigValue + 1;
    }

    private DataType(String swigName, DataType swigEnum) {
        this.swigName = swigName;
        this.swigValue = swigEnum.swigValue;
        swigNext = this.swigValue + 1;
    }

    public static DataType swigToEnum(int swigValue) {
        if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
            return swigValues[swigValue];
        for (int i = 0; i < swigValues.length; i++)
            if (swigValues[i].swigValue == swigValue)
                return swigValues[i];
        throw new IllegalArgumentException("No enum " + DataType.class + " with value " + swigValue);
    }

    public final int swigValue() {
        return swigValue;
    }

    public String toString() {
        return swigName;
    }
}

