/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package monad.jni;

public final class DataCommandType {
    public final static DataCommandType PUT = new DataCommandType("PUT", CMonadJNI.PUT_get());
    public final static DataCommandType DEL = new DataCommandType("DEL", CMonadJNI.DEL_get());
    public final static DataCommandType UPDATE = new DataCommandType("UPDATE", CMonadJNI.UPDATE_get());
    public final static DataCommandType COMMAND_UNKNOWN = new DataCommandType("COMMAND_UNKNOWN", CMonadJNI.COMMAND_UNKNOWN_get());
    private static DataCommandType[] swigValues = {PUT, DEL, UPDATE, COMMAND_UNKNOWN};
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;

    private DataCommandType(String swigName) {
        this.swigName = swigName;
        this.swigValue = swigNext++;
    }

    private DataCommandType(String swigName, int swigValue) {
        this.swigName = swigName;
        this.swigValue = swigValue;
        swigNext = swigValue + 1;
    }

    private DataCommandType(String swigName, DataCommandType swigEnum) {
        this.swigName = swigName;
        this.swigValue = swigEnum.swigValue;
        swigNext = this.swigValue + 1;
    }

    public static DataCommandType swigToEnum(int swigValue) {
        if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
            return swigValues[swigValue];
        for (int i = 0; i < swigValues.length; i++)
            if (swigValues[i].swigValue == swigValue)
                return swigValues[i];
        throw new IllegalArgumentException("No enum " + DataCommandType.class + " with value " + swigValue);
    }

    public final int swigValue() {
        return swigValue;
    }

    public String toString() {
        return swigName;
    }
}

