/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package monad.jni;

public class NodeIdNoSQL extends NoSQLSupport {
    private long swigCPtr;

    protected NodeIdNoSQL(long cPtr, boolean cMemoryOwn) {
        super(CMonadJNI.NodeIdNoSQL_SWIGUpcast(cPtr), cMemoryOwn);
        swigCPtr = cPtr;
    }

    public NodeIdNoSQL(String db_path, NoSQLOptions options) {
        this(CMonadJNI.new_NodeIdNoSQL(db_path, NoSQLOptions.getCPtr(options), options), true);
    }

    protected static long getCPtr(NodeIdNoSQL obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                CMonadJNI.delete_NodeIdNoSQL(swigCPtr);
            }
            swigCPtr = 0;
        }
        super.delete();
    }

    public byte[] GetId(int id_seq) {
        return CMonadJNI.NodeIdNoSQL_GetId(swigCPtr, this, id_seq);
    }

    public int GetIdSeq(byte[] id) {
        return CMonadJNI.NodeIdNoSQL_GetIdSeq(swigCPtr, this, id);
    }

}
