/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package monad.jni;

public class NodeNoSQL extends NoSQLSupport {
    private long swigCPtr;

    protected NodeNoSQL(long cPtr, boolean cMemoryOwn) {
        super(CMonadJNI.NodeNoSQL_SWIGUpcast(cPtr), cMemoryOwn);
        swigCPtr = cPtr;
    }

    public NodeNoSQL(String db_path, NoSQLOptions options) {
        this(CMonadJNI.new_NodeNoSQL(db_path, NoSQLOptions.getCPtr(options), options), true);
    }

    protected static long getCPtr(NodeNoSQL obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                CMonadJNI.delete_NodeNoSQL(swigCPtr);
            }
            swigCPtr = 0;
        }
        super.delete();
    }

    public void SetIdNoSQL(NodeIdNoSQL id_nosql) {
        CMonadJNI.NodeNoSQL_SetIdNoSQL(swigCPtr, this, NodeIdNoSQL.getCPtr(id_nosql), id_nosql);
    }

    public byte[] Get(byte[] key) {
        return CMonadJNI.NodeNoSQL_Get(swigCPtr, this, key);
    }

    public byte[] FindNextBinlog(long seq) {
        return CMonadJNI.NodeNoSQL_FindNextBinlog(swigCPtr, this, seq);
    }

    public byte[] GetId(long id_seq) {
        return CMonadJNI.NodeNoSQL_GetId(swigCPtr, this, id_seq);
    }

    public StatusType Del(byte[] key) {
        return StatusType.swigToEnum(CMonadJNI.NodeNoSQL_Del(swigCPtr, this, key));
    }

    public long GetLastLogSeq() {
        return CMonadJNI.NodeNoSQL_GetLastLogSeq(swigCPtr, this);
    }

    public void DeleteBinlog(long last_seq) {
        CMonadJNI.NodeNoSQL_DeleteBinlog(swigCPtr, this, last_seq);
    }

    public StatusType StartSyncData(String sync_server_endpoint, String resource_name, short server_id) {
        return StatusType.swigToEnum(CMonadJNI.NodeNoSQL_StartSyncData(swigCPtr, this, sync_server_endpoint, resource_name, server_id));
    }

    public void SyncDataWorker(String sync_server_endpoint, String resource_name, short region_id) {
        CMonadJNI.NodeNoSQL_SyncDataWorker(swigCPtr, this, sync_server_endpoint, resource_name, region_id);
    }

    public long DoSyncData(String sync_server_endpoint, String resource_name, short server_id) {
        return CMonadJNI.NodeNoSQL_DoSyncData(swigCPtr, this, sync_server_endpoint, resource_name, server_id);
    }

    public void StopNoSQL() {
        CMonadJNI.NodeNoSQL_StopNoSQL(swigCPtr, this);
    }

}
