/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package monad.jni;

public class NoSQLSupport {
    protected boolean swigCMemOwn;
    private long swigCPtr;

    NoSQLSupport(long cPtr, boolean cMemoryOwn) {
        swigCPtr = cPtr;
        //swigCMemOwn = cMemoryOwn;
        swigCMemOwn = true;
    }

    public NoSQLSupport(String db_path, NoSQLOptions options) {
        this(CMonadJNI.new_NoSQLSupport(db_path, NoSQLOptions.getCPtr(options), options), true);
    }

    static long getCPtr(NoSQLSupport obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                CMonadJNI.delete_NoSQLSupport(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public byte[] RawGet(byte[] key) {
        return CMonadJNI.NoSQLSupport_RawGet(swigCPtr, this, key);
    }

    public StatusType RawPut(byte[] key, byte[] val) {
        return StatusType.swigToEnum(CMonadJNI.NoSQLSupport_RawPut(swigCPtr, this, key, val));
    }

    public int GetDataStatCount() {
        return CMonadJNI.NoSQLSupport_GetDataStatCount(swigCPtr, this);
    }

}
