/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package monad.jni;

public class NoSQLOptions {
    protected boolean swigCMemOwn;
    private long swigCPtr;

    NoSQLOptions(long cPtr, boolean cMemoryOwn) {
        swigCPtr = cPtr;
        //swigCMemOwn = cMemoryOwn;
        swigCMemOwn = true;
    }

    public NoSQLOptions() {
        this(CMonadJNI.new_NoSQLOptions(), true);
    }

    static long getCPtr(NoSQLOptions obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                CMonadJNI.delete_NoSQLOptions(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public long getCache_size_mb() {
        return CMonadJNI.NoSQLOptions_cache_size_mb_get(swigCPtr, this);
    }

    public void setCache_size_mb(long value) {
        CMonadJNI.NoSQLOptions_cache_size_mb_set(swigCPtr, this, value);
    }

    public long getWrite_buffer_mb() {
        return CMonadJNI.NoSQLOptions_write_buffer_mb_get(swigCPtr, this);
    }

    public void setWrite_buffer_mb(long value) {
        CMonadJNI.NoSQLOptions_write_buffer_mb_set(swigCPtr, this, value);
    }

    public long getMax_open_files() {
        return CMonadJNI.NoSQLOptions_max_open_files_get(swigCPtr, this);
    }

    public void setMax_open_files(long value) {
        CMonadJNI.NoSQLOptions_max_open_files_set(swigCPtr, this, value);
    }

    public long getLog_keeped_num() {
        return CMonadJNI.NoSQLOptions_log_keeped_num_get(swigCPtr, this);
    }

    public void setLog_keeped_num(long value) {
        CMonadJNI.NoSQLOptions_log_keeped_num_set(swigCPtr, this, value);
    }

}
