/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package monad.jni;

public final class StatusType {
    public final static StatusType S_OK = new StatusType("S_OK", CMonadJNI.S_OK_get());
    public final static StatusType E_DATA_SAVE = new StatusType("E_DATA_SAVE", CMonadJNI.E_DATA_SAVE_get());
    public final static StatusType E_GET = new StatusType("E_GET", CMonadJNI.E_GET_get());
    public final static StatusType E_DATA_DELETE = new StatusType("E_DATA_DELETE", CMonadJNI.E_DATA_DELETE_get());
    public final static StatusType E_ELEMENT_NOT_FOUND = new StatusType("E_ELEMENT_NOT_FOUND", CMonadJNI.E_ELEMENT_NOT_FOUND_get());
    public final static StatusType E_NO_NODE_SERVER = new StatusType("E_NO_NODE_SERVER", CMonadJNI.E_NO_NODE_SERVER_get());
    public final static StatusType E_DATA_NOT_FOUND = new StatusType("E_DATA_NOT_FOUND", CMonadJNI.E_DATA_NOT_FOUND_get());
    public final static StatusType E_FAIL_TO_COMMIT = new StatusType("E_FAIL_TO_COMMIT", CMonadJNI.E_FAIL_TO_COMMIT_get());
    public final static StatusType E_INSTANCE_IS_NULL = new StatusType("E_INSTANCE_IS_NULL", CMonadJNI.E_INSTANCE_IS_NULL_get());
    public final static StatusType E_ID_SERVER_NOT_SET = new StatusType("E_ID_SERVER_NOT_SET", CMonadJNI.E_ID_SERVER_NOT_SET_get());
    private static StatusType[] swigValues = {S_OK, E_DATA_SAVE, E_GET, E_DATA_DELETE, E_ELEMENT_NOT_FOUND, E_NO_NODE_SERVER, E_DATA_NOT_FOUND, E_FAIL_TO_COMMIT, E_INSTANCE_IS_NULL, E_ID_SERVER_NOT_SET};
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;

    private StatusType(String swigName) {
        this.swigName = swigName;
        this.swigValue = swigNext++;
    }

    private StatusType(String swigName, int swigValue) {
        this.swigName = swigName;
        this.swigValue = swigValue;
        swigNext = swigValue + 1;
    }

    private StatusType(String swigName, StatusType swigEnum) {
        this.swigName = swigName;
        this.swigValue = swigEnum.swigValue;
        swigNext = this.swigValue + 1;
    }

    public static StatusType swigToEnum(int swigValue) {
        if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
            return swigValues[swigValue];
        for (int i = 0; i < swigValues.length; i++)
            if (swigValues[i].swigValue == swigValue)
                return swigValues[i];
        throw new IllegalArgumentException("No enum " + StatusType.class + " with value " + swigValue);
    }

    public final int swigValue() {
        return swigValue;
    }

    public String toString() {
        return swigName;
    }
}

