/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package monad.jni;

public class SyncIdNoSQL extends NoSQLSupport {
    private long swigCPtr;

    protected SyncIdNoSQL(long cPtr, boolean cMemoryOwn) {
        super(CMonadJNI.SyncIdNoSQL_SWIGUpcast(cPtr), cMemoryOwn);
        swigCPtr = cPtr;
    }

    public SyncIdNoSQL(String db_path, NoSQLOptions options) {
        this(CMonadJNI.new_SyncIdNoSQL(db_path, NoSQLOptions.getCPtr(options), options), true);
    }

    protected static long getCPtr(SyncIdNoSQL obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                CMonadJNI.delete_SyncIdNoSQL(swigCPtr);
            }
            swigCPtr = 0;
        }
        super.delete();
    }

    public int FindRegionMaxIdSeq(short region_id) {
        return CMonadJNI.SyncIdNoSQL_FindRegionMaxIdSeq(swigCPtr, this, region_id);
    }

    public void AddRegion(short region_id) {
        CMonadJNI.SyncIdNoSQL_AddRegion(swigCPtr, this, region_id);
    }

    public void RemoveRegion(short region_id) {
        CMonadJNI.SyncIdNoSQL_RemoveRegion(swigCPtr, this, region_id);
    }

}
