/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package monad.jni;

public class SyncNoSQLManager {
    protected boolean swigCMemOwn;
    private long swigCPtr;

    SyncNoSQLManager(long cPtr, boolean cMemoryOwn) {
        swigCPtr = cPtr;
        //swigCMemOwn = cMemoryOwn;
        swigCMemOwn = true;
    }

    public SyncNoSQLManager() {
        this(CMonadJNI.new_SyncNoSQLManager(), true);
    }

    static long getCPtr(SyncNoSQLManager obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                CMonadJNI.delete_SyncNoSQLManager(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public StatusType AddInstance(String resource_name, SyncNoSQL instance) {
        return StatusType.swigToEnum(CMonadJNI.SyncNoSQLManager_AddInstance(swigCPtr, this, resource_name, SyncNoSQL.getCPtr(instance), instance));
    }

    public StatusType RemoveInstance(String resource_name) {
        return StatusType.swigToEnum(CMonadJNI.SyncNoSQLManager_RemoveInstance(swigCPtr, this, resource_name));
    }

    public SyncNoSQL FindInstanceByHash(long hash) {
        long cPtr = CMonadJNI.SyncNoSQLManager_FindInstanceByHash(swigCPtr, this, hash);
        return (cPtr == 0) ? null : new SyncNoSQL(cPtr, false);
    }

    public SyncNoSQL FindInstanceByName(String name) {
        long cPtr = CMonadJNI.SyncNoSQLManager_FindInstanceByName(swigCPtr, this, name);
        return (cPtr == 0) ? null : new SyncNoSQL(cPtr, false);
    }

}
