/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package monad.jni;

public class SyncServer extends SyncNoSQLManager {
    private long swigCPtr;

    protected SyncServer(long cPtr, boolean cMemoryOwn) {
        super(CMonadJNI.SyncServer_SWIGUpcast(cPtr), cMemoryOwn);
        swigCPtr = cPtr;
    }

    public SyncServer() {
        this(CMonadJNI.new_SyncServer(), true);
    }

    protected static long getCPtr(SyncServer obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                CMonadJNI.delete_SyncServer(swigCPtr);
            }
            swigCPtr = 0;
        }
        super.delete();
    }

    public StatusType Start(String address) {
        return StatusType.swigToEnum(CMonadJNI.SyncServer_Start(swigCPtr, this, address));
    }

    public StatusType StartWorkers(int thread_num) {
        return StatusType.swigToEnum(CMonadJNI.SyncServer_StartWorkers(swigCPtr, this, thread_num));
    }

    public void StopServer() {
        CMonadJNI.SyncServer_StopServer(swigCPtr, this);
    }

}
